[ MOSIP-21222 ] updated prereg batch job helm/chart

diff --git a/deployment/sandbox-v2/helm/charts/prereg/templates/batch-dep.yaml b/deployment/sandbox-v2/helm/charts/prereg/templates/batch-dep.yaml
--- a/deployment/sandbox-v2/helm/charts/prereg/templates/batch-dep.yaml
+++ b/deployment/sandbox-v2/helm/charts/prereg/templates/batch-dep.yaml
@@ -48,23 +48,47 @@ spec:
         ports:
         - containerPort: {{ .Values.services.batch.ports.containerPort }}
         readinessProbe:
-          httpGet:
-            path: {{ .Values.services.batch.healthUrl }}
-            port: {{ .Values.services.batch.ports.containerPort }}
+          exec:
+            command:
+              - /bin/bash
+              - -c
+              - HEALTH_CHECK_PATHS="http://prereg-application-service:80/preregistration/v1/actuator/health";
+                for str in $HEALTH_CHECK_PATHS; do
+                curl_output="$(curl -w %{http_code} -o /dev/null -s $str)";
+                if ! [ "$curl_output" = "200" ]; then
+                echo "$str failed with status code $curl_output" >> /dev/stderr && exit 1;
+                fi;
+                done
           periodSeconds: {{ .Values.probe.period }}
           timeoutSeconds: {{ .Values.probe.timeout }}
           failureThreshold: {{ .Values.probe.failureThreshold }}
         livenessProbe:
-          httpGet:
-            path: {{ .Values.services.batch.healthUrl }}
-            port: {{ .Values.services.batch.ports.containerPort }}
+          exec:
+            command:
+              - /bin/bash
+              - -c
+              - HEALTH_CHECK_PATHS="http://prereg-application-service:80/preregistration/v1/actuator/health";
+                for str in $HEALTH_CHECK_PATHS; do
+                curl_output="$(curl -w %{http_code} -o /dev/null -s $str)";
+                if ! [ "$curl_output" = "200" ]; then
+                echo "$str failed with status code $curl_output" >> /dev/stderr && exit 1;
+                fi;
+                done
           periodSeconds: {{ .Values.probe.livenessPeriod }}
           timeoutSeconds: {{ .Values.probe.timeout }}
           failureThreshold: {{ .Values.probe.failureThreshold }}
         startupProbe:
-          httpGet:
-            path: {{ .Values.services.batch.healthUrl }}
-            port: {{ .Values.services.batch.ports.containerPort }}
+          exec:
+            command:
+              - /bin/bash
+              - -c
+              - HEALTH_CHECK_PATHS="http://prereg-application-service:80/preregistration/v1/actuator/health";
+                for str in $HEALTH_CHECK_PATHS; do
+                curl_output="$(curl -w %{http_code} -o /dev/null -s $str)";
+                if ! [ "$curl_output" = "200" ]; then
+                echo "$str failed with status code $curl_output" >> /dev/stderr && exit 1;
+                fi;
+                done
           failureThreshold: {{ .Values.probe.failureThreshold }}
           periodSeconds: {{ .Values.probe.startupPeriod }}
           timeoutSeconds: {{ .Values.probe.timeout }}
